### PR TITLE
Add PHP 8.3 to CI

### PR DESCRIPTION
**Pull request by dereuromark**
And it is sufficient to test each min/max of minors, even the min/max of majors usually suffices within PHP.

### CODE REVIEW

**Comment by mlocati** [comment]
> And it is sufficient to test each min/max of minors, even the min/max of majors usually suffices within PHP.

I'd disagree: it's better to test every single Major.Minor version of PHP.

**Comment by dereuromark** [comment]
There is no logical reason in doing so, I can say that with confidence over thousands of repos and years of experience
Only creates more waiting time and burns resources :)
But do what you must.

**Comment by dereuromark** [comment]
Your problem here seems to be of different kind anyway.
I will close this then and leave this to the maintainers.

**Comment by mlocati** [comment]
> There is no logical reason in doing so, I can say that with confidence over thousands of repos and years of experience

I can say that 35 years of coding have taught me that it's better to never assume anything :wink:



> Your problem here seems to be of different kind anyway.

What do you mean?

**Comment by dereuromark** [comment]
Well, I still have worked professionally for decades in that specific field :)
Assuming is the thing you do right now

> What do you mean?

See failing CI for 8.3

**Comment by mlocati** [comment]
> Well, I still have worked professionally for decades in that specific field :)

Me too.

> Assuming is the thing you do right now

Yep, both for work (daily) and for a ton of open source projects.

I don't get the reason why you are so malign: you should reconsider the way you approach people you don't know.

**Comment by dereuromark** [comment]
There is no malign. I am telling you the facts and logical reason.

I find it rather not helpful to have experts giving you advice and trying to help you keeping this (currently not so well maintained) repo maintained such an answer.
So count me out - good luck moving forward.

**Pull request closed without merging**
