### PR TITLE
[FEATURE] Run tests against PHP > 8.1

### PR DESCRIPTION
**Pull request by NicoHaase**

### CODE REVIEW

**Comment by mlocati** [comment]
I think we also need to update https://github.com/php-imagine/docker-builder

**Comment by NicoHaase** [comment]
> I think we also need to update [php-imagine/docker-builder](https://github.com/php-imagine/docker-builder)

Yep, looks like that... but I don't really get how to fix the workflow (see https://github.com/NicoHaase/docker-builder/actions) - a lot of the older PHP versions won't built properly

**Comment by mlocati** [comment]
> Yep, looks like that... but I don't really get how to fix the workflow (see https://github.com/NicoHaase/docker-builder/actions) - a lot of the older PHP versions won't built properly

Fixed

**Comment by mlocati** [comment]
Superseded by #865

**Pull request closed without merging**
